<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrewAndCastSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            [
                'project_id' => 2,
                'nick_name' => 'Ricky',
                'full_name' => 'Ricky R Setiyawan',
                'job_title' => 'Producer',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/KTSLF7HT26CVhAYe6i0a.jpeg',
                'date_birth' => '1993-03-15 00:00:00',
                'address' => 'Cilandak, Jakarta Selatan',
                'home_town' => 'Malang',
                'group' => 'Producer Team',
                'category' => 'crew',
                'email' => 'ricky@skakstudios.com',
                'phone' => '081216384261',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Bayu SKAK',
                'full_name' => 'Bayu Eko Moektito',
                'job_title' => 'Director',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/SUjRPkdgGBA79nlOEVCr.jpeg',
                'date_birth' => null,
                'address' => 'Fatmawati, Jakarta Selatan',
                'home_town' => 'Malang',
                'group' => 'Director Team',
                'category' => 'crew',
                'email' => 'bayuskak@skakstudios.com',
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Yudhis PW',
                'full_name' => null,
                'job_title' => 'Assistant Director 1',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Director Team',
                'category' => 'crew',
                'email' => 'yudhis@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Tretan Muslim',
                'full_name' => 'Aditya Muslim',
                'job_title' => 'Lead Actor',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/IsJwo4UDGdDUIdRjFq4X.webp',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => null,
                'phone' => null,
                'character_name' => 'Muslim',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Rini',
                'full_name' => 'Rini Atmodjo',
                'job_title' => 'Line Producer',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/PVYveKg3FgWWxbxrdgNJ.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Producer Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Bangkit',
                'full_name' => null,
                'job_title' => 'Assistant Director 2',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/R2edz0tZURVDgwnT6ayE.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Director Team',
                'category' => 'crew',
                'email' => 'Bangkit@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Clara',
                'full_name' => null,
                'job_title' => 'Make Up Beauty n Effects',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/8pIfNdMMKkw9xiViDdsq.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Make Up Team',
                'category' => 'crew',
                'email' => 'clara@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Ari',
                'full_name' => null,
                'job_title' => 'Art Director',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Art Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Rofiq',
                'full_name' => 'Achmad Rofiq',
                'job_title' => 'Head IP Development',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/zlD9V9TXnJ4oypluRPr1.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Development Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Icol',
                'full_name' => 'Achmad Faishol',
                'job_title' => 'Writer',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/ATNLaaCcWTFjYWxEaFqg/pub/XvSNSDo9P7QqI1rXsSNU.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Development Team',
                'category' => 'crew',
                'email' => 'ach.faishol@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Fadel',
                'full_name' => 'M Fadel Raihan',
                'job_title' => 'Visual Development',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/GA7i9j7Lm6yMCWZG17qk.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Development Team',
                'category' => 'crew',
                'email' => 'Conceptartist@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Hebz',
                'full_name' => 'Hafshoh Mubarak',
                'job_title' => 'Casting Director',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/ATNLaaCcWTFjYWxEaFqg/pub/iA1d4gZDu2ps3iNBxbjV.jpeg',
                'date_birth' => '2025-02-18 14:59:00',
                'address' => null,
                'home_town' => null,
                'group' => 'Casting Team',
                'category' => 'crew',
                'email' => 'Hebz@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Dian',
                'full_name' => null,
                'job_title' => 'Location Manager',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/AU0zmW12UlTYZ5Oo18zo.jpeg',
                'date_birth' => '2025-02-18 15:51:00',
                'address' => null,
                'home_town' => null,
                'group' => 'Production Team',
                'category' => 'crew',
                'email' => 'Dian@gmail.com',
                'phone' => '0',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Hasanudin Bugo',
                'full_name' => null,
                'job_title' => 'Sound Recordist',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/7ywr5f2p4tQ2wMNbYiUX.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Sound Team',
                'category' => 'crew',
                'email' => 'Hasanudin@gmail.com',
                'phone' => '089513334957',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Jeane Elizabeth Fam',
                'full_name' => null,
                'job_title' => 'Wardrobe',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/ZTjSbLJFTWDRMBMFRE4m.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Wardrobe Team',
                'category' => 'crew',
                'email' => 'Jeane@gmail.com',
                'phone' => '089513334957',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Biandi Gagah Syahputra',
                'full_name' => null,
                'job_title' => 'Script Continity',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/ulZTTEC6KRkFeY97EoqM.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Director Team',
                'category' => 'crew',
                'email' => 'biandi@gmail.com',
                'phone' => '089513334957',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Widi Krisna',
                'full_name' => 'Widi Krisna Widodo',
                'job_title' => 'Character Design',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/aH4X0LlSRbLmb0AxplAO.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Development Team',
                'category' => 'crew',
                'email' => 'widikrisna@gmail.com',
                'phone' => '081',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Robert',
                'full_name' => 'Herry Robert',
                'job_title' => 'DOP',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/W9VdKHU0FpXk1MR6r7HZ.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'DOP Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Habib',
                'full_name' => null,
                'job_title' => 'Production Finance',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/KBJaO8Ivz73N8B31D5P5.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Production Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Mike',
                'full_name' => 'Mike R',
                'job_title' => 'Production Assistant 1',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/KltZoWBAzbQofc0ozuFP.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Production Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Raihan',
                'full_name' => null,
                'job_title' => 'Production Assistant 2',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/WlyocoWBDsRCO0UFjqD7.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Production Team',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Zukal',
                'full_name' => 'Zukal Rosyidin',
                'job_title' => 'Brand Designer',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/QEbCEcbBgRWNrgsletsr.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Visual Design',
                'category' => 'crew',
                'email' => null,
                'phone' => null,
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Alvin',
                'full_name' => 'Alvin Hariz',
                'job_title' => 'Poster Designer',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/LQRE9oBvF6hF1e5u0WNg.jpeg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Visual Design',
                'category' => 'crew',
                'email' => 'alvi@gmail.com',
                'phone' => '0892',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Bambang Ceper',
                'full_name' => 'Bambang Kurniyawan',
                'job_title' => 'Stand In FOUFO',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'bambangkurniawan@gmail.com',
                'phone' => '-',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Ade Bibir',
                'full_name' => 'Ade Kurniyawan',
                'job_title' => 'Dubber',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'ade@gmail.com',
                'phone' => '0990',
                'character_name' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Hari Otong',
                'full_name' => 'Hari Ramadhan',
                'job_title' => 'Supporting Actor',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/SqsoBCYqITdp1TGrHQO7.jpg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'hari@gmail.com',
                'phone' => '08912412',
                'character_name' => 'Kacong',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Fuad',
                'full_name' => 'Fuad Sasmita',
                'job_title' => 'Supporting Actor',
                'image' => 'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/NQAHcDNVDV3cYycBJx0c/pub/9FoXvyE1Zvci4NeSfU8Q.jpg',
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'fuad@gmail.com',
                'phone' => '0814211',
                'character_name' => 'Ipul',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Mieke Sahir',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'mieke@gmail.com',
                'phone' => '01812312',
                'character_name' => 'Nur',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Anggun Dwi Lestari',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'anggun@gmail.com',
                'phone' => '0123712431',
                'character_name' => 'Siti',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Mahendra',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'mahendra@gmail.com',
                'phone' => '0912478141',
                'character_name' => 'Latif',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Rifki',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'rifki@gmail.com',
                'phone' => '9178414',
                'character_name' => 'Mustofa',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Ina Pogang',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'ina@gmail.com',
                'phone' => '12031841',
                'character_name' => 'Aqeela',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Ade Kurniyawan',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'ade@gmail.com',
                'phone' => '0128413',
                'character_name' => 'Toni',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Sukkur Jember',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'sukur@gmail.com',
                'phone' => '091724123',
                'character_name' => 'Mat Saleh',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Beni Siregar',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'beni@gmail.com',
                'phone' => '098771231',
                'character_name' => 'Cokro',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Bayu SKAK',
                'full_name' => 'Bayu Eko Moektito',
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'bayu@gmail.com',
                'phone' => '0842343',
                'character_name' => 'Joko',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Indra Pramujito',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'indra@gmail.com',
                'phone' => '9971412',
                'character_name' => 'Riki',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'nick_name' => 'Karina Affandi',
                'full_name' => null,
                'job_title' => 'Supporting Actor',
                'image' => null,
                'date_birth' => null,
                'address' => null,
                'home_town' => null,
                'group' => 'Main Cast',
                'category' => 'cast',
                'email' => 'karina@gmail.com',
                'phone' => '908182421',
                'character_name' => 'Ika',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Lanjutkan untuk data lainnya...
        ];

        DB::table('crew_and_casts')->insert($data);

    }
}
